name: TDG
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run tdg-github-action
      uses: ribtoks/tdg-github-action@master
      with:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}
        SHA: ${{ github.sha }}
        REF: ${{ github.ref }}
        MIN_WORDS: 0
        MIN_CHARACTERS: 0
        LABEL: "tdg-autogen"
        EXTENDED_LABELS: 0
        COMMENT_ON_ISSUES: 1
